# Default values for storageos.
# This is a YAML-formatted file.
# Declare variables to be passed into your templates.
image:
  repository: storageos/node
  tag: 1.0.0-rc1
  pullPolicy: IfNotPresent

## does your cluster have rbac enabled? assume no by default
rbacEnabled: true

cluster:
  # to generate a join token see:
  # https://docs.storageos.com/docs/install/prerequisites/clusterdiscovery
  join: 

  # sharedDir should be set if running kubelet in a container.  This should
  # be the path shared into to kubelet container, typically:
  # "/var/lib/kubelet/plugins/kubernetes.io~storageos".  If not set, defaults
  # will be used.
  sharedDir:
storageclass:
  name: fast
  pool: default
  fsType: ext4
api:
  secretName: storageos-api
  secretNamespace: default
  # secrets are namespace specific, create 1+N for every namespace.
  address: storageos:5705
  # address is used to generate the ApiAddress value in the secret. This
  # updated later with the service ClusterIP which is not known yet.
  username: storageos
  password: storageos
namespace: storageos
service:
  name: storageos
  type: ClusterIP
  externalPort: 5705
  internalPort: 5705
resources: {}

csi:
  enable: false
  # provisionCreds is credentials for volume create and delete operations.
  provisionCreds:
    enable: false
    username: username1
    password: password1
    secretName: storageos-provision-creds
  # controllerPublishCreds is credentials for controller volume publish and unpublish operations.
  controllerPublishCreds:
    enable: false
    username: username2
    password: password2
    secretName: storageos-ctrl-publish-creds
  # nodeStageCreds is credentials for node volume stage operations.
  nodeStageCreds:
    enable: false
    username: username3
    password: password3
    secretName: storageos-node-stage-creds
  # nodePublishCreds is credentials for node volume publish operations.
  nodePublishCreds:
    enable: false
    username: username4
    password: password4
    secretName: storageos-node-publish-creds
